Refactor/update icons
TeskaLabs/seacat-auth-webui pull request #29
Opened 2023-05-03 07:05 UTC by Samsunggora

2023-05-11 15:19 UTC, Pe5h4 commented
@Samsunggora Ok, this looks good, dont forget to update asab-webui submodule, when it will be ready/approved

2023-05-15 19:38 UTC, Pe5h4 commented
@Samsunggora Resolve conflicts pls

2023-05-16 20:37 UTC, petrKavulok requested changes

2023-05-16 20:37 UTC, petrKavulok commented on CHANGELOG.md
> +- Changed icons from coreui.io icons to atlasicons. (INDIGO Sprint 230428, [!29](https://github.com/TeskaLabs/seacat-auth-webui/pull/29))
Please update sprint number.

2023-05-16 20:37 UTC, petrKavulok commented on CHANGELOG.md
> +- Changed icons from coreui.io icons to atlasicons. (INDIGO Sprint 230428, [!29](https://github.com/TeskaLabs/seacat-auth-webui/pull/29))
Also, don't forget to version bump asab-webui sumbodule

2023-08-07 15:27 UTC, merged