Refactor/favicon-update
TeskaLabs/seacat-auth-webui pull request #34
Opened 2023-06-26 13:19 UTC by petrKavulok

### in this PR 
- favicon assets were updated with new logo
- asab-webui submodule update

2023-06-26 15:48 UTC, Pe5h4 requested changes
@petrKavulok Looks good. Just one issue I have found. Please check

2023-06-26 15:48 UTC, Pe5h4 commented on public/media/teskalabs/img/favicon/favicon-template-395x395-cropped.png
@petrKavulok Is this even used? I cant find the reference so I suppose this is obsolete and should be removed/correctly named

2023-06-27 07:46 UTC, petrKavulok commented on public/media/teskalabs/img/favicon/favicon-template-395x395-cropped.png
ugh.. yes, sorry. This is the file I used as a template to create the other, smaller logos. It was included by accident

2023-07-10 16:19 UTC, Pe5h4 requested changes

2023-07-10 16:19 UTC, Pe5h4 commented on CHANGELOG.md
> +- ASAB WebUI submodule version bump [[3a35738](https://github.com/TeskaLabs/asab-webui/commit/3a3573806e2964efbf5e5bb02c15acc9af41c8ac)] commit (INDIGO Sprint 230623, [!34](https://github.com/TeskaLa
@petrKavulok Dont update submodule in changelog in already released version. It has no use, instead put it to a release candidate :)

2023-07-11 16:21 UTC, Pe5h4 approved these changes

2023-07-12 07:53 UTC, merged