Refactor/load background
TeskaLabs/seacat-auth-webui pull request #4
Opened 2022-09-15 10:36 UTC by Aringoaway

The first time this file is loaded, it should have the correct background

2022-09-15 11:06 UTC, Aringoaway commented
Network: Regular 3G

How it looks like with brighter colours. Red is static `backgound-color: pink;`, blue is used via variables `background-color: $link-color;`
![dcol](https://user-images.githubusercontent.com/65866093/190388449-8e873723-f944-445a-91fc-7e2f258aa012.gif)



How it looks with normal colors
![stcol](https://user-images.githubusercontent.com/65866093/190387912-a37b9e59-32fb-467b-99c4-8a7ce68e8209.gif)

2022-09-15 15:02 UTC, Pe5h4 requested changes
@Aringoaway Pls add changes to changelog

2022-09-15 15:02 UTC, Pe5h4 commented on public/styles.css
> +    background-color: pink;
@Aringoaway We dont want to have a pink color as a background

2022-09-15 15:02 UTC, Pe5h4 commented on src/index.js
> +window.addEventListener('load', (event) => {
@Aringoaway Write a description here pls

2022-09-15 15:02 UTC, Pe5h4 commented on public/index.html
> +		<link rel="stylesheet" href="styles.css">
@Aringoaway Where is the spinner?

2022-09-19 13:14 UTC, Aringoaway commented
@Pe5h4  Add spinner 
Network: Regular 2G
![spinner](https://user-images.githubusercontent.com/65866093/191025546-b4ac5061-7ffe-41a2-a492-e607c1cbc2fc.gif)

2022-09-19 14:44 UTC, Pe5h4 approved these changes
@Aringoaway Ok, this looks better

2022-09-19 14:46 UTC, Pe5h4 requested changes

2022-09-19 14:46 UTC, Pe5h4 commented on CHANGELOG.md
> +## Refactoring
@Aringoaway You have `Refactoring` two times in the CHANGELOG, pls update

2022-09-19 19:15 UTC, ateska approved these changes

2022-09-21 16:12 UTC, Pe5h4 approved these changes
@Aringoaway Pls resolve conflicts before merging

2022-09-27 08:00 UTC, merged