Refactor/penrose-background
TeskaLabs/seacat-auth-webui pull request #40
Opened 2023-08-07 14:29 UTC by queuing4oranges

- adding new component to utils that will generate the Penrose background and resize the background when the window size changes
- adding the `generatePenrose`to all relevant screens

"can't login" screen and resizing

https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/b156e4c0-005d-4c2a-af8a-5b83f08456b9

all screens

https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/cc7ce2d9-94e4-4aca-ab09-ded62330647b

different browser /testing resizing

https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/2d766278-0179-417b-8504-e4e039945923

2023-08-08 09:40 UTC, queuing4oranges commented on src/modules/auth/containers/LoginScreen.js
> -	function useWindowSize() {
the `useWindowSize` is only being used to measure and then re-create background when screen size changes (same was in RegisterScreen) 

it's now part of the `generatePenrose` function

2023-08-11 14:19 UTC, Pe5h4 requested changes
Alright, this looks very good. Please test that also on invitation (but this should look the same I suppose)

2023-08-11 14:19 UTC, Pe5h4 commented on src/modules/auth/utils/generatePenrose.js
> +}
@queuing4oranges No new line at the end of the file

2023-08-11 15:36 UTC, ateska approved these changes

2023-08-24 09:53 UTC, queuing4oranges commented
- tested on invitation
- added also to password reset

![penrose-invitation-diffuser](https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/251aec1d-eb7c-44ad-8e3f-1b6ee381eca9)

![penrose-invitation](https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/0c374a92-ddc5-43df-9fed-678c00d905e6)

![penrose-reset-pw](https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/c045f547-9bcc-4fa3-bd8c-64d036dc2838)

![penrose-reset-pw2](https://github.com/TeskaLabs/seacat-auth-webui/assets/31582696/cf17e33c-315b-4add-970f-eefae295a6e4)

2023-08-25 14:47 UTC, Pe5h4 approved these changes

2023-08-28 08:25 UTC, merged